$('#core').prepend('<div class="header">')
$('.header').append('<div class="logohead">')
$('.logohead').append('<h1 id="headtext">SKYBROOK FOUNDATION</h1>')
$('.header').append('</div>')
$('.header').append('<div id="spacer"></div>')
$('.header').append('<div class="menu">')
$('.menu').append('<div class="mainmenu">')
$('.mainmenu').append('<ul id="menulist">')
$('#menulist').append('<x id="menuitem"><a href="index.html">Home</a>','</x>')
$('#menulist').append(' | ')
$('#menulist').append('<x id="menuitem"><a href="resources.html">Resources</a>','</x>')
$('#menulist').append(' | ')
$('#menulist').append('<x id="menuitem"><a href="about.html">About</a>','</x>')
$('.mainmenu').append('</ul>')
$('.menu').append('</div>')
$('.header').append('</div>')

// End of Header
// Begin of footer
$('#core').append('<div id="footer">')
$('#footer').append('<div id="footContent">')
$('#footContent').append('<p id="copyrightNotice">boilerplate here</p>')

$('#footer').append('</div>')
$('#core').append('</div>')
